In [1]:
import tensorflow as tf
import numpy as np

In [8]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [13]:
def soft_margin_softmax(x, m):
    numerator = np.exp(x - m)
    sum = 0
    for i in range(x.size):
        sum += np.exp(x[i])
    denominator = np.zeros(x.size)
    for i in range(x.size):
        denominator[i] = sum - np.exp(x[i]) + np.exp(x[i] - m)
    return np.divide(numerator, denominator)
        

In [ ]:
def convert_to_softmax(input_tensor):
    denominator = tf.Variable(0, dtype=tf.float32)
    result = tf.Variable(tf.zeros(input_tensor.get_shape()))

    denominator = tf.reduce_sum(tf.map_fn(lambda x: tf.exp(tf.convert_to_tensor(x)), input_tensor))
    exponent_tensor = tf.exp(input_tensor)
    result = tf.divide(exponent_tensor, denominator)
    
    return result

In [6]:
def convert_to_soft_margin_softmax(input_tensor, m):
    denominator = tf.Variable(0, dtype=tf.float32)
    result = tf.Variable(tf.zeros(input_tensor.get_shape()))
    
    sum_of_exponents = tf.reduce_sum(tf.map_fn(lambda x: tf.exp(tf.convert_to_tensor(x)), input_tensor))
    exponent_tensor = tf.exp(input_tensor)
    temp = tf.exp(tf.constant(m, dtype=tf.float32, shape=input_tensor.get_shape()))
    numerator = tf.divide(exponent_tensor, temp)
    denominator = tf.subtract(tf.add(numerator, sum_of_exponents), exponent_tensor)
    result = tf.divide(numerator, denominator)
    
    return result

In [21]:
input_array = np.random.rand(6)
print(input_array)
input_tensor = tf.convert_to_tensor(input_array, dtype=tf.float32)
m = 0
softmax_tensor = convert_to_soft_margin_softmax(input_tensor, 0)

model=tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(softmax_tensor))
    
print(softmax(input_array))
print(soft_margin_softmax(input_array, 0))

[0.95517053 0.10724936 0.37210907 0.73057553 0.47426189 0.26681918]
[0.25601926 0.10965418 0.14290659 0.20451833 0.15827659 0.128625  ]
[0.25601927 0.10965417 0.1429066  0.20451835 0.15827659 0.12862502]
[0.25601927 0.10965417 0.1429066  0.20451835 0.15827659 0.12862502]
